<?php

/**
 * @file
 * Main functions of the module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function virtual_entities_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.virtual_entities':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides the "Virtual Entities" to a Drupal website.') . '</p>';

      return $output;
  }
}
