virtual_entities.virtual_entity_type.*:
  type: config_entity
  label: 'Virtual entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    description:
      type: text
      label: 'Description'
    endpoint:
      type: string
      label: 'Endpoint'
    read_only:
      type: boolean
      label: 'Read only'
    entities_identity:
      type: string
      label: 'Entities identity'
    parameters:
      type: mapping
      label: 'Parameters'
      mapping:
        list:
          type: sequence
          sequence:
            type: sequence
            label: 'List parameter'
            sequence:
              type: string
        single:
          type: sequence
          sequence:
            type: sequence
            label: 'Single load parameter'
            sequence:
              type: string
    api_key_settings:
      type: mapping
      label: 'API key settings'
      mapping:
        header_name:
          type: string
          label: 'API key header name'
        key:
          type: string
          label: 'API key'
    client:
      type: string
      label: 'Storage client'
    format:
      type: string
      label: 'Format'
    field_mappings:
      type: sequence
      label: 'Field mappings'
      sequence:
        type: string
        label: 'Field mapping'
